### ISSUE TITLE
Indicate docker image name in README?

### ISSUE THREAD

**Issue by cboettig** [NESCent/popgen-docker#15]
README should probably match https://hub.docker.com/r/hlapp/rpopgen/ , currently it's not clear how to pull the image or where it is built. (If no long description is manually entered on Docker Hub, it will automatically use the README from GitHub anyway).  

btw, do you use the "linked repository" setting in "build settings" tab of the Docker Hub to automate rebuilds when the upstream image changes?

**Comment by hlapp** [comment]
> btw, do you use the "linked repository" setting in "build settings" tab of the Docker Hub to automate rebuilds when the upstream image changes?

Yes. Which reminds me that I now need to change this to rocker/tidyverse.

**Comment by hlapp** [comment]
The image is built on/by Docker Hub.

**Comment by hlapp** [comment]
Also, @cboettig, regarding how to pull the image, I had held that due to #1, on which you never commented. Can you render a decision there so we can move forward one way or another?

**Comment by hlapp** [comment]
See #18. Will add full name of Docker image as which one would pull it.
