### ISSUE TITLE
pcadapt has been removed from CRAN

### ISSUE THREAD

**Issue by hlapp** [NESCent/popgen-docker#23]
Lately all auto-triggered builds on Docker Hub fail for [pcadapt](http://membres-timc.imag.fr/Michael.Blum/PCAdapt.html):
```
Error: package ‘pcadapt’ is not available (for R version 3.4.3)
In addition: Warning message:
package ‘pcadapt’ is not available (for R version 3.4.3) 
```

It turns out that pcadapt apparently has [been removed from CRAN](https://cran.r-project.org/web/packages/pcadapt/index.html) on Feb 21, 2018, for "policy violations". The latest version archived on CRAN is v3.0.4.

However, a more recent version [is available on Github](https://github.com/bcm-uga/pcadapt). I suppose what needs to happen is install from Github instead of from CRAN?

@keurcien are there plans to reinstate the package on CRAN shortly, or will this take more time, and hence we should be changing the container to install pcadapt from Github instead?

**Comment by keurcien** [comment]
Hi,

Yeah we have been working on this, it should be available in less than 2
weeks. Thanks for the notice.

Best,

Keurcien

2018-03-04 0:08 GMT+01:00 Hilmar Lapp <notifications@github.com>:

**Comment by hlapp** [comment]
> Yeah we have been working on this, it should be available in less than 2 weeks.

Hi @keurcien - any update meanwhile on where you're at with having it back on CRAN proper? If this is proving difficult, perhaps it's better for us to change to installing from Github.

**Comment by keurcien** [comment]
Hi,

We have submitted the package but we are still waiting for CRAN's approval.
Otherwise you can use the GitHub version, it shouldn't differ too much.

Best,

Keurcien

2018-03-26 2:35 GMT+02:00 Hilmar Lapp <notifications@github.com>:

**Comment by zkamvar** [comment]
Hi @keurcien,

Is there any update?

**Comment by keurcien** [comment]
Hi @zkamvar, 

So sorry, it's taking a little longer as expected. We've fixed a couple of errors, now there's one error that is not spotted by CRAN automatic check, but that does not pass the actual CRAN check, so it's a little harder to debug. Should be back soon though, I will have more time next week to do it.

**Comment by hlapp** [comment]
`pcadapt` is back on Github. I'm wondering whether we should go back to installing from CRAN, or leave it at installing from Github?

**Comment by zkamvar** [comment]
I'll try the container locally and see if it works out of the tin. I'm assuming if it's on CRAN, it should be safe to install. Am I right in that assumption, @keurcien?

**Comment by keurcien** [comment]
Hi, 

Can you tell me what version of pcadapt were u using?
The new version is safe to install but there's a couple of things that have changed and it'd probably need some (slight) adjustments in any code that was running the 3.0.4 version. I might be wrong though. Tell me what code you have (if you have tests for example) and I can fix that for you if you want.

**Comment by zkamvar** [comment]
We are using version 4.0.2 from June 2018:

```
pcadapt     * 4.0.2   2018-06-07 Github (bcm-uga/pcadapt@97da966)
```

I suppose there are no breaking changes between 4.0.2 and 4.0.3?

**Comment by zkamvar** [comment]
AFAICT, the only code that uses pcadapt lives here: https://popgen.nescent.org/2016-01-26-SNP-selection.html#section-2-pcadapt

**Comment by keurcien** [comment]
Then it should work fine :)

**Comment by hlapp** [comment]
Package is back on CRAN, and since #30 (and v0.2.12) that is again where we obtain it from.
